// TODO: Operation `acc.attach`.
// TODO: Operation `acc.bounds`.
// TODO: Operation `acc.copyin`.
// TODO: Operation `acc.copyout`.
// TODO: Operation `acc.create`.
// TODO: Operation `acc.data`.
// TODO: Operation `acc.delete`.
// TODO: Operation `acc.detach`.
// TODO: Operation `acc.deviceptr`.
// TODO: Operation `acc.enter_data`.
// TODO: Operation `acc.exit_data`.
// TODO: Operation `acc.firstprivate.recipe`.
// TODO: Operation `acc.getdeviceptr`.
// TODO: Operation `acc.host_data`.
// TODO: Operation `acc.init`.
// TODO: Operation `acc.kernels`.
// TODO: Operation `acc.loop`.
// TODO: Operation `acc.nocreate`.
// TODO: Operation `acc.parallel`.
// TODO: Operation `acc.present`.
// TODO: Operation `acc.private.recipe`.
// TODO: Operation `acc.reduction.recipe`.
// TODO: Operation `acc.serial`.
// TODO: Operation `acc.shutdown`.
// TODO: Operation `acc.terminator`.
// TODO: Operation `acc.update`.
// TODO: Operation `acc.update_device`.
// TODO: Operation `acc.update_host`.
// TODO: Operation `acc.use_device`.
// TODO: Operation `acc.wait`.
// TODO: Operation `acc.yield`.
