// TODO: Operation `affine.apply`.
// TODO: Operation `affine.delinearize_index`.
// TODO: Operation `affine.for`.
// TODO: Operation `affine.if`.
// TODO: Operation `affine.load`.
// TODO: Operation `affine.max`.
// TODO: Operation `affine.min`.
// TODO: Operation `affine.parallel`.
// TODO: Operation `affine.prefetch`.
// TODO: Operation `affine.store`.
// TODO: Operation `affine.vector_load`.
// TODO: Operation `affine.vector_store`.
// TODO: Operation `affine.yield`.
// TODO: Operation `affine.dma_start`.
// TODO: Operation `affine.dma_wait`.
