// TODO: Operation `amdgpu.lds_barrier`.
// TODO: Operation `amdgpu.mfma`.
// TODO: Operation `amdgpu.raw_buffer_atomic_cmpswap`.
// TODO: Operation `amdgpu.raw_buffer_atomic_fadd`.
// TODO: Operation `amdgpu.raw_buffer_atomic_fmax`.
// TODO: Operation `amdgpu.raw_buffer_atomic_smax`.
// TODO: Operation `amdgpu.raw_buffer_atomic_umin`.
// TODO: Operation `amdgpu.raw_buffer_load`.
// TODO: Operation `amdgpu.raw_buffer_store`.
