// TODO: Operation `arith.addf`.
// TODO: Operation `arith.addi`.
// TODO: Operation `arith.addui_extended`.
// TODO: Operation `arith.andi`.
// TODO: Operation `arith.bitcast`.
// TODO: Operation `arith.ceildivsi`.
// TODO: Operation `arith.ceildivui`.
// TODO: Operation `arith.cmpf`.
// TODO: Operation `arith.cmpi`.
// TODO: Operation `arith.constant`.
// TODO: Operation `arith.divf`.
// TODO: Operation `arith.divsi`.
// TODO: Operation `arith.divui`.
// TODO: Operation `arith.extf`.
// TODO: Operation `arith.extsi`.
// TODO: Operation `arith.extui`.
// TODO: Operation `arith.fptosi`.
// TODO: Operation `arith.fptoui`.
// TODO: Operation `arith.floordivsi`.
// TODO: Operation `arith.index_cast`.
// TODO: Operation `arith.index_castui`.
// TODO: Operation `arith.maxf`.
// TODO: Operation `arith.maxsi`.
// TODO: Operation `arith.maxui`.
// TODO: Operation `arith.minf`.
// TODO: Operation `arith.minsi`.
// TODO: Operation `arith.minui`.
// TODO: Operation `arith.mulf`.
// TODO: Operation `arith.muli`.
// TODO: Operation `arith.mulsi_extended`.
// TODO: Operation `arith.mului_extended`.
// TODO: Operation `arith.negf`.
// TODO: Operation `arith.ori`.
// TODO: Operation `arith.remf`.
// TODO: Operation `arith.remsi`.
// TODO: Operation `arith.remui`.
// TODO: Operation `arith.sitofp`.
// TODO: Operation `arith.shli`.
// TODO: Operation `arith.shrsi`.
// TODO: Operation `arith.shrui`.
// TODO: Operation `arith.subf`.
// TODO: Operation `arith.subi`.
// TODO: Operation `arith.truncf`.
// TODO: Operation `arith.trunci`.
// TODO: Operation `arith.uitofp`.
// TODO: Operation `arith.xori`.
// TODO: Operation `arith.select`.
