// TODO: Operation `async.add_to_group`.
// TODO: Operation `async.await_all`.
// TODO: Operation `async.await`.
// TODO: Operation `async.call`.
// TODO: Operation `async.coro.begin`.
// TODO: Operation `async.coro.end`.
// TODO: Operation `async.coro.free`.
// TODO: Operation `async.coro.id`.
// TODO: Operation `async.coro.save`.
// TODO: Operation `async.coro.suspend`.
// TODO: Operation `async.create_group`.
// TODO: Operation `async.execute`.
// TODO: Operation `async.func`.
// TODO: Operation `async.return`.
// TODO: Operation `async.runtime.add_ref`.
// TODO: Operation `async.runtime.add_to_group`.
// TODO: Operation `async.runtime.await_and_resume`.
// TODO: Operation `async.runtime.await`.
// TODO: Operation `async.runtime.create_group`.
// TODO: Operation `async.runtime.create`.
// TODO: Operation `async.runtime.drop_ref`.
// TODO: Operation `async.runtime.is_error`.
// TODO: Operation `async.runtime.load`.
// TODO: Operation `async.runtime.num_worker_threads`.
// TODO: Operation `async.runtime.resume`.
// TODO: Operation `async.runtime.set_available`.
// TODO: Operation `async.runtime.set_error`.
// TODO: Operation `async.runtime.store`.
// TODO: Operation `async.yield`.
