// TODO: Operation `gpu.all_reduce`.
// TODO: Operation `gpu.alloc`.
// TODO: Operation `gpu.barrier`.
// TODO: Operation `gpu.block_dim`.
// TODO: Operation `gpu.block_id`.
// TODO: Operation `gpu.create_coo`.
// TODO: Operation `gpu.create_csr`.
// TODO: Operation `gpu.create_dn_mat`.
// TODO: Operation `gpu.create_dn_vec`.
// TODO: Operation `gpu.create_sparse_env`.
// TODO: Operation `gpu.dealloc`.
// TODO: Operation `gpu.destroy_dn_mat`.
// TODO: Operation `gpu.destroy_dn_vec`.
// TODO: Operation `gpu.destroy_sp_vec`.
// TODO: Operation `gpu.destroy_sparse_env`.
// TODO: Operation `gpu.func`.
// TODO: Operation `gpu.module`.
// TODO: Operation `gpu.global_id`.
// TODO: Operation `gpu.grid_dim`.
// TODO: Operation `gpu.host_register`.
// TODO: Operation `gpu.host_unregister`.
// TODO: Operation `gpu.lane_id`.
// TODO: Operation `gpu.launch_func`.
// TODO: Operation `gpu.launch`.
// TODO: Operation `gpu.memcpy`.
// TODO: Operation `gpu.memset`.
// TODO: Operation `gpu.module_end`.
// TODO: Operation `gpu.num_subgroups`.
// TODO: Operation `gpu.printf`.
// TODO: Operation `gpu.return`.
// TODO: Operation `gpu.sddmm_buffer_size`.
// TODO: Operation `gpu.sddmm`.
// TODO: Operation `gpu.set_default_device`.
// TODO: Operation `gpu.shuffle`.
// TODO: Operation `gpu.spmm_buffer_size`.
// TODO: Operation `gpu.spmm`.
// TODO: Operation `gpu.spmv_buffer_size`.
// TODO: Operation `gpu.spmv`.
// TODO: Operation `gpu.subgroup_id`.
// TODO: Operation `gpu.subgroup_mma_compute`.
// TODO: Operation `gpu.subgroup_mma_constant_matrix`.
// TODO: Operation `gpu.subgroup_mma_elementwise`.
// TODO: Operation `gpu.subgroup_mma_load_matrix`.
// TODO: Operation `gpu.subgroup_mma_store_matrix`.
// TODO: Operation `gpu.subgroup_reduce`.
// TODO: Operation `gpu.subgroup_size`.
// TODO: Operation `gpu.terminator`.
// TODO: Operation `gpu.thread_id`.
// TODO: Operation `gpu.wait`.
// TODO: Operation `gpu.yield`.
