// TODO: Operation `index.add`.
// TODO: Operation `index.and`.
// TODO: Operation `index.bool.constant`.
// TODO: Operation `index.casts`.
// TODO: Operation `index.castu`.
// TODO: Operation `index.ceildivs`.
// TODO: Operation `index.ceildivu`.
// TODO: Operation `index.cmp`.
// TODO: Operation `index.constant`.
// TODO: Operation `index.divs`.
// TODO: Operation `index.divu`.
// TODO: Operation `index.floordivs`.
// TODO: Operation `index.maxs`.
// TODO: Operation `index.maxu`.
// TODO: Operation `index.mins`.
// TODO: Operation `index.minu`.
// TODO: Operation `index.mul`.
// TODO: Operation `index.or`.
// TODO: Operation `index.rems`.
// TODO: Operation `index.remu`.
// TODO: Operation `index.shl`.
// TODO: Operation `index.shrs`.
// TODO: Operation `index.shru`.
// TODO: Operation `index.sizeof`.
// TODO: Operation `index.sub`.
// TODO: Operation `index.xor`.
