// TODO: Operation `linalg.batch_matmul`.
// TODO: Operation `linalg.batch_matmul_transpose_b`.
// TODO: Operation `linalg.batch_matvec`.
// TODO: Operation `linalg.batch_reduce_matmul`.
// TODO: Operation `linalg.broadcast`.
// TODO: Operation `linalg.conv_1d_ncw_fcw`.
// TODO: Operation `linalg.conv_1d_nwc_wcf`.
// TODO: Operation `linalg.conv_1d`.
// TODO: Operation `linalg.conv_2d_nchw_fchw`.
// TODO: Operation `linalg.conv_2d_ngchw_fgchw`.
// TODO: Operation `linalg.conv_2d_nhwc_fhwc`.
// TODO: Operation `linalg.conv_2d_nhwc_hwcf`.
// TODO: Operation `linalg.conv_2d_nhwc_hwcf_q`.
// TODO: Operation `linalg.conv_2d`.
// TODO: Operation `linalg.conv_3d_ncdhw_fcdhw`.
// TODO: Operation `linalg.conv_3d_ndhwc_dhwcf`.
// TODO: Operation `linalg.conv_3d_ndhwc_dhwcf_q`.
// TODO: Operation `linalg.conv_3d`.
// TODO: Operation `linalg.copy`.
// TODO: Operation `linalg.depthwise_conv_1d_ncw_cw`.
// TODO: Operation `linalg.depthwise_conv_1d_nwc_wc`.
// TODO: Operation `linalg.depthwise_conv_1d_nwc_wcm`.
// TODO: Operation `linalg.depthwise_conv_2d_nchw_chw`.
// TODO: Operation `linalg.depthwise_conv_2d_nhwc_hwc`.
// TODO: Operation `linalg.depthwise_conv_2d_nhwc_hwc_q`.
// TODO: Operation `linalg.depthwise_conv_2d_nhwc_hwcm`.
// TODO: Operation `linalg.depthwise_conv_2d_nhwc_hwcm_q`.
// TODO: Operation `linalg.depthwise_conv_3d_ncdhw_cdhw`.
// TODO: Operation `linalg.depthwise_conv_3d_ndhwc_dhwcm`.
// TODO: Operation `linalg.dot`.
// TODO: Operation `linalg.elementwise_binary`.
// TODO: Operation `linalg.elementwise_unary`.
// TODO: Operation `linalg.fill`.
// TODO: Operation `linalg.fill_rng_2d`.
// TODO: Operation `linalg.generic`.
// TODO: Operation `linalg.index`.
// TODO: Operation `linalg.yield`.
// TODO: Operation `linalg.map`.
// TODO: Operation `linalg.matmul`.
// TODO: Operation `linalg.matmul_transpose_b`.
// TODO: Operation `linalg.matmul_unsigned`.
// TODO: Operation `linalg.matvec`.
// TODO: Operation `linalg.mmt4d`.
// TODO: Operation `linalg.pooling_nchw_max`.
// TODO: Operation `linalg.pooling_nchw_sum`.
// TODO: Operation `linalg.pooling_ncw_max`.
// TODO: Operation `linalg.pooling_ncw_sum`.
// TODO: Operation `linalg.pooling_ndhwc_max`.
// TODO: Operation `linalg.pooling_ndhwc_min`.
// TODO: Operation `linalg.pooling_ndhwc_sum`.
// TODO: Operation `linalg.pooling_nhwc_max`.
// TODO: Operation `linalg.pooling_nhwc_max_unsigned`.
// TODO: Operation `linalg.pooling_nhwc_min`.
// TODO: Operation `linalg.pooling_nhwc_min_unsigned`.
// TODO: Operation `linalg.pooling_nhwc_sum`.
// TODO: Operation `linalg.pooling_nwc_max`.
// TODO: Operation `linalg.pooling_nwc_max_unsigned`.
// TODO: Operation `linalg.pooling_nwc_min`.
// TODO: Operation `linalg.pooling_nwc_min_unsigned`.
// TODO: Operation `linalg.pooling_nwc_sum`.
// TODO: Operation `linalg.quantized_batch_matmul`.
// TODO: Operation `linalg.quantized_matmul`.
// TODO: Operation `linalg.reduce`.
// TODO: Operation `linalg.transpose`.
// TODO: Operation `linalg.vecmat`.
