// TODO: Operation `llvm.access_group`.
// TODO: Operation `llvm.add`.
// TODO: Operation `llvm.addrspacecast`.
// TODO: Operation `llvm.alias_scope_domain`.
// TODO: Operation `llvm.alias_scope`.
// TODO: Operation `llvm.alloca`.
// TODO: Operation `llvm.and`.
// TODO: Operation `llvm.ashr`.
// TODO: Operation `llvm.atomicrmw`.
// TODO: Operation `llvm.bitcast`.
// TODO: Operation `llvm.br`.
// TODO: Operation `llvm.call_intrinsic`.
// TODO: Operation `llvm.call`.
// TODO: Operation `llvm.cmpxchg`.
// TODO: Operation `llvm.cond_br`.
// TODO: Operation `llvm.extractelement`.
// TODO: Operation `llvm.extractvalue`.
// TODO: Operation `llvm.fadd`.
// TODO: Operation `llvm.fcmp`.
// TODO: Operation `llvm.fdiv`.
// TODO: Operation `llvm.fence`.
// TODO: Operation `llvm.fmul`.
// TODO: Operation `llvm.fneg`.
// TODO: Operation `llvm.fpext`.
// TODO: Operation `llvm.fptosi`.
// TODO: Operation `llvm.fptoui`.
// TODO: Operation `llvm.fptrunc`.
// TODO: Operation `llvm.freeze`.
// TODO: Operation `llvm.frem`.
// TODO: Operation `llvm.fsub`.
// TODO: Operation `llvm.func`.
// TODO: Operation `llvm.getelementptr`.
// TODO: Operation `llvm.icmp`.
// TODO: Operation `llvm.inline_asm`.
// TODO: Operation `llvm.insertelement`.
// TODO: Operation `llvm.insertvalue`.
// TODO: Operation `llvm.intr.abs`.
// TODO: Operation `llvm.intr.assume`.
// TODO: Operation `llvm.intr.bitreverse`.
// TODO: Operation `llvm.intr.bswap`.
// TODO: Operation `llvm.intr.ceil`.
// TODO: Operation `llvm.intr.copysign`.
// TODO: Operation `llvm.intr.coro.align`.
// TODO: Operation `llvm.intr.coro.begin`.
// TODO: Operation `llvm.intr.coro.end`.
// TODO: Operation `llvm.intr.coro.free`.
// TODO: Operation `llvm.intr.coro.id`.
// TODO: Operation `llvm.intr.coro.resume`.
// TODO: Operation `llvm.intr.coro.save`.
// TODO: Operation `llvm.intr.coro.size`.
// TODO: Operation `llvm.intr.coro.suspend`.
// TODO: Operation `llvm.intr.cos`.
// TODO: Operation `llvm.intr.ctlz`.
// TODO: Operation `llvm.intr.ctpop`.
// TODO: Operation `llvm.intr.cttz`.
// TODO: Operation `llvm.intr.dbg.declare`.
// TODO: Operation `llvm.intr.dbg.value`.
// TODO: Operation `llvm.intr.debugtrap`.
// TODO: Operation `llvm.intr.eh.typeid.for`.
// TODO: Operation `llvm.intr.exp`.
// TODO: Operation `llvm.intr.exp2`.
// TODO: Operation `llvm.intr.expect.with.probability`.
// TODO: Operation `llvm.intr.expect`.
// TODO: Operation `llvm.intr.experimental.noalias.scope.decl`.
// TODO: Operation `llvm.intr.experimental.stepvector`.
// TODO: Operation `llvm.intr.experimental.vp.strided.load`.
// TODO: Operation `llvm.intr.experimental.vp.strided.store`.
// TODO: Operation `llvm.intr.fabs`.
// TODO: Operation `llvm.intr.floor`.
// TODO: Operation `llvm.intr.fma`.
// TODO: Operation `llvm.intr.fmuladd`.
// TODO: Operation `llvm.intr.fshl`.
// TODO: Operation `llvm.intr.fshr`.
// TODO: Operation `llvm.intr.get.active.lane.mask`.
// TODO: Operation `llvm.intr.is.constant`.
// TODO: Operation `llvm.intr.is.fpclass`.
// TODO: Operation `llvm.intr.lifetime.end`.
// TODO: Operation `llvm.intr.lifetime.start`.
// TODO: Operation `llvm.intr.llrint`.
// TODO: Operation `llvm.intr.llround`.
// TODO: Operation `llvm.intr.log`.
// TODO: Operation `llvm.intr.log10`.
// TODO: Operation `llvm.intr.log2`.
// TODO: Operation `llvm.intr.lrint`.
// TODO: Operation `llvm.intr.lround`.
// TODO: Operation `llvm.intr.masked.compressstore`.
// TODO: Operation `llvm.intr.masked.expandload`.
// TODO: Operation `llvm.intr.masked.gather`.
// TODO: Operation `llvm.intr.masked.load`.
// TODO: Operation `llvm.intr.masked.scatter`.
// TODO: Operation `llvm.intr.masked.store`.
// TODO: Operation `llvm.intr.matrix.column.major.load`.
// TODO: Operation `llvm.intr.matrix.column.major.store`.
// TODO: Operation `llvm.intr.matrix.multiply`.
// TODO: Operation `llvm.intr.matrix.transpose`.
// TODO: Operation `llvm.intr.maximum`.
// TODO: Operation `llvm.intr.maxnum`.
// TODO: Operation `llvm.intr.memcpy.inline`.
// TODO: Operation `llvm.intr.memcpy`.
// TODO: Operation `llvm.intr.memmove`.
// TODO: Operation `llvm.intr.memset`.
// TODO: Operation `llvm.intr.minimum`.
// TODO: Operation `llvm.intr.minnum`.
// TODO: Operation `llvm.intr.nearbyint`.
// TODO: Operation `llvm.intr.pow`.
// TODO: Operation `llvm.intr.powi`.
// TODO: Operation `llvm.intr.prefetch`.
// TODO: Operation `llvm.intr.rint`.
// TODO: Operation `llvm.intr.round`.
// TODO: Operation `llvm.intr.roundeven`.
// TODO: Operation `llvm.intr.sadd.sat`.
// TODO: Operation `llvm.intr.sadd.with.overflow`.
// TODO: Operation `llvm.intr.sin`.
// TODO: Operation `llvm.intr.smax`.
// TODO: Operation `llvm.intr.smin`.
// TODO: Operation `llvm.intr.smul.with.overflow`.
// TODO: Operation `llvm.intr.sqrt`.
// TODO: Operation `llvm.intr.sshl.sat`.
// TODO: Operation `llvm.intr.ssub.sat`.
// TODO: Operation `llvm.intr.ssub.with.overflow`.
// TODO: Operation `llvm.intr.stackrestore`.
// TODO: Operation `llvm.intr.stacksave`.
// TODO: Operation `llvm.intr.threadlocal.address`.
// TODO: Operation `llvm.intr.trap`.
// TODO: Operation `llvm.intr.trunc`.
// TODO: Operation `llvm.intr.uadd.sat`.
// TODO: Operation `llvm.intr.uadd.with.overflow`.
// TODO: Operation `llvm.intr.ubsantrap`.
// TODO: Operation `llvm.intr.umax`.
// TODO: Operation `llvm.intr.umin`.
// TODO: Operation `llvm.intr.umul.with.overflow`.
// TODO: Operation `llvm.intr.ushl.sat`.
// TODO: Operation `llvm.intr.usub.sat`.
// TODO: Operation `llvm.intr.usub.with.overflow`.
// TODO: Operation `llvm.intr.vacopy`.
// TODO: Operation `llvm.intr.vaend`.
// TODO: Operation `llvm.intr.vastart`.
// TODO: Operation `llvm.intr.vector.extract`.
// TODO: Operation `llvm.intr.vector.insert`.
// TODO: Operation `llvm.intr.vector.reduce.add`.
// TODO: Operation `llvm.intr.vector.reduce.and`.
// TODO: Operation `llvm.intr.vector.reduce.fadd`.
// TODO: Operation `llvm.intr.vector.reduce.fmax`.
// TODO: Operation `llvm.intr.vector.reduce.fmin`.
// TODO: Operation `llvm.intr.vector.reduce.fmul`.
// TODO: Operation `llvm.intr.vector.reduce.mul`.
// TODO: Operation `llvm.intr.vector.reduce.or`.
// TODO: Operation `llvm.intr.vector.reduce.smax`.
// TODO: Operation `llvm.intr.vector.reduce.smin`.
// TODO: Operation `llvm.intr.vector.reduce.umax`.
// TODO: Operation `llvm.intr.vector.reduce.umin`.
// TODO: Operation `llvm.intr.vector.reduce.xor`.
// TODO: Operation `llvm.intr.vp.add`.
// TODO: Operation `llvm.intr.vp.and`.
// TODO: Operation `llvm.intr.vp.ashr`.
// TODO: Operation `llvm.intr.vp.fadd`.
// TODO: Operation `llvm.intr.vp.fdiv`.
// TODO: Operation `llvm.intr.vp.fma`.
// TODO: Operation `llvm.intr.vp.fmul`.
// TODO: Operation `llvm.intr.vp.fmuladd`.
// TODO: Operation `llvm.intr.vp.fneg`.
// TODO: Operation `llvm.intr.vp.fpext`.
// TODO: Operation `llvm.intr.vp.fptosi`.
// TODO: Operation `llvm.intr.vp.fptoui`.
// TODO: Operation `llvm.intr.vp.fptrunc`.
// TODO: Operation `llvm.intr.vp.frem`.
// TODO: Operation `llvm.intr.vp.fsub`.
// TODO: Operation `llvm.intr.vp.inttoptr`.
// TODO: Operation `llvm.intr.vp.load`.
// TODO: Operation `llvm.intr.vp.lshr`.
// TODO: Operation `llvm.intr.vp.merge`.
// TODO: Operation `llvm.intr.vp.mul`.
// TODO: Operation `llvm.intr.vp.or`.
// TODO: Operation `llvm.intr.vp.ptrtoint`.
// TODO: Operation `llvm.intr.vp.reduce.add`.
// TODO: Operation `llvm.intr.vp.reduce.and`.
// TODO: Operation `llvm.intr.vp.reduce.fadd`.
// TODO: Operation `llvm.intr.vp.reduce.fmax`.
// TODO: Operation `llvm.intr.vp.reduce.fmin`.
// TODO: Operation `llvm.intr.vp.reduce.fmul`.
// TODO: Operation `llvm.intr.vp.reduce.mul`.
// TODO: Operation `llvm.intr.vp.reduce.or`.
// TODO: Operation `llvm.intr.vp.reduce.smax`.
// TODO: Operation `llvm.intr.vp.reduce.smin`.
// TODO: Operation `llvm.intr.vp.reduce.umax`.
// TODO: Operation `llvm.intr.vp.reduce.umin`.
// TODO: Operation `llvm.intr.vp.reduce.xor`.
// TODO: Operation `llvm.intr.vp.sdiv`.
// TODO: Operation `llvm.intr.vp.select`.
// TODO: Operation `llvm.intr.vp.sext`.
// TODO: Operation `llvm.intr.vp.shl`.
// TODO: Operation `llvm.intr.vp.sitofp`.
// TODO: Operation `llvm.intr.vp.srem`.
// TODO: Operation `llvm.intr.vp.store`.
// TODO: Operation `llvm.intr.vp.sub`.
// TODO: Operation `llvm.intr.vp.trunc`.
// TODO: Operation `llvm.intr.vp.udiv`.
// TODO: Operation `llvm.intr.vp.uitofp`.
// TODO: Operation `llvm.intr.vp.urem`.
// TODO: Operation `llvm.intr.vp.xor`.
// TODO: Operation `llvm.intr.vp.zext`.
// TODO: Operation `llvm.intr.vscale`.
// TODO: Operation `llvm.inttoptr`.
// TODO: Operation `llvm.invoke`.
// TODO: Operation `llvm.landingpad`.
// TODO: Operation `llvm.load`.
// TODO: Operation `llvm.lshr`.
// TODO: Operation `llvm.metadata`.
// TODO: Operation `llvm.mlir.addressof`.
// TODO: Operation `llvm.mlir.constant`.
// TODO: Operation `llvm.mlir.global_ctors`.
// TODO: Operation `llvm.mlir.global_dtors`.
// TODO: Operation `llvm.mlir.global`.
// TODO: Operation `llvm.mlir.null`.
// TODO: Operation `llvm.mlir.poison`.
// TODO: Operation `llvm.mlir.undef`.
// TODO: Operation `llvm.mul`.
// TODO: Operation `llvm.or`.
// TODO: Operation `llvm.ptrtoint`.
// TODO: Operation `llvm.resume`.
// TODO: Operation `llvm.return`.
// TODO: Operation `llvm.sdiv`.
// TODO: Operation `llvm.select`.
// TODO: Operation `llvm.sext`.
// TODO: Operation `llvm.shl`.
// TODO: Operation `llvm.shufflevector`.
// TODO: Operation `llvm.sitofp`.
// TODO: Operation `llvm.srem`.
// TODO: Operation `llvm.store`.
// TODO: Operation `llvm.sub`.
// TODO: Operation `llvm.switch`.
// TODO: Operation `llvm.tbaa_root`.
// TODO: Operation `llvm.tbaa_tag`.
// TODO: Operation `llvm.tbaa_type_desc`.
// TODO: Operation `llvm.trunc`.
// TODO: Operation `llvm.udiv`.
// TODO: Operation `llvm.uitofp`.
// TODO: Operation `llvm.unreachable`.
// TODO: Operation `llvm.urem`.
// TODO: Operation `llvm.xor`.
// TODO: Operation `llvm.zext`.
