// TODO: Operation `math.absf`.
// TODO: Operation `math.absi`.
// TODO: Operation `math.atan2`.
// TODO: Operation `math.atan`.
// TODO: Operation `math.cbrt`.
// TODO: Operation `math.ceil`.
// TODO: Operation `math.copysign`.
// TODO: Operation `math.cos`.
// TODO: Operation `math.ctlz`.
// TODO: Operation `math.cttz`.
// TODO: Operation `math.ctpop`.
// TODO: Operation `math.erf`.
// TODO: Operation `math.exp2`.
// TODO: Operation `math.expm1`.
// TODO: Operation `math.exp`.
// TODO: Operation `math.fpowi`.
// TODO: Operation `math.floor`.
// TODO: Operation `math.fma`.
// TODO: Operation `math.ipowi`.
// TODO: Operation `math.log10`.
// TODO: Operation `math.log1p`.
// TODO: Operation `math.log2`.
// TODO: Operation `math.log`.
// TODO: Operation `math.powf`.
// TODO: Operation `math.roundeven`.
// TODO: Operation `math.round`.
// TODO: Operation `math.rsqrt`.
// TODO: Operation `math.sin`.
// TODO: Operation `math.sqrt`.
// TODO: Operation `math.tan`.
// TODO: Operation `math.tanh`.
// TODO: Operation `math.trunc`.
