// TODO: Operation `memref.assume_alignment`.
// TODO: Operation `memref.atomic_rmw`.
// TODO: Operation `memref.atomic_yield`.
// TODO: Operation `memref.copy`.
// TODO: Operation `memref.generic_atomic_rmw`.
// TODO: Operation `memref.load`.
// TODO: Operation `memref.alloc`.
// TODO: Operation `memref.alloca`.
// TODO: Operation `memref.alloca_scope`.
// TODO: Operation `memref.alloca_scope.return`.
// TODO: Operation `memref.cast`.
// TODO: Operation `memref.collapse_shape`.
// TODO: Operation `memref.dealloc`.
// TODO: Operation `memref.dim`.
// TODO: Operation `memref.dma_start`.
// TODO: Operation `memref.dma_wait`.
// TODO: Operation `memref.expand_shape`.
// TODO: Operation `memref.extract_aligned_pointer_as_index`.
// TODO: Operation `memref.extract_strided_metadata`.
// TODO: Operation `memref.get_global`.
// TODO: Operation `memref.global`.
// TODO: Operation `memref.memory_space_cast`.
// TODO: Operation `memref.prefetch`.
// TODO: Operation `memref.rank`.
// TODO: Operation `memref.realloc`.
// TODO: Operation `memref.reinterpret_cast`.
// TODO: Operation `memref.reshape`.
// TODO: Operation `memref.store`.
// TODO: Operation `memref.transpose`.
// TODO: Operation `memref.view`.
// TODO: Operation `memref.subview`.
// TODO: Operation `memref.tensor_store`.
// TODO: Operation `memref.dma_start`.
// TODO: Operation `memref.dma_wait`.
