// TODO: Operation `ml_program.func`.
// TODO: Operation `ml_program.global_load_const`.
// TODO: Operation `ml_program.global_load_graph`.
// TODO: Operation `ml_program.global_load`.
// TODO: Operation `ml_program.global_store_graph`.
// TODO: Operation `ml_program.global_store`.
// TODO: Operation `ml_program.global`.
// TODO: Operation `ml_program.output`.
// TODO: Operation `ml_program.return`.
// TODO: Operation `ml_program.subgraph`.
// TODO: Operation `ml_program.token`.
