// TODO: Operation `nvvm.bar.warp.sync`.
// TODO: Operation `nvvm.barrier0`.
// TODO: Operation `nvvm.cp.async.commit.group`.
// TODO: Operation `nvvm.cp.async.shared.global`.
// TODO: Operation `nvvm.cp.async.wait.group`.
// TODO: Operation `nvvm.ldmatrix`.
// TODO: Operation `nvvm.mma.sync`.
// TODO: Operation `nvvm.rcp.approx.ftz.f`.
// TODO: Operation `nvvm.read.ptx.sreg.ctaid.x`.
// TODO: Operation `nvvm.read.ptx.sreg.ctaid.y`.
// TODO: Operation `nvvm.read.ptx.sreg.ctaid.z`.
// TODO: Operation `nvvm.read.ptx.sreg.laneid`.
// TODO: Operation `nvvm.read.ptx.sreg.nctaid.x`.
// TODO: Operation `nvvm.read.ptx.sreg.nctaid.y`.
// TODO: Operation `nvvm.read.ptx.sreg.nctaid.z`.
// TODO: Operation `nvvm.read.ptx.sreg.ntid.x`.
// TODO: Operation `nvvm.read.ptx.sreg.ntid.y`.
// TODO: Operation `nvvm.read.ptx.sreg.ntid.z`.
// TODO: Operation `nvvm.read.ptx.sreg.tid.x`.
// TODO: Operation `nvvm.read.ptx.sreg.tid.y`.
// TODO: Operation `nvvm.read.ptx.sreg.tid.z`.
// TODO: Operation `nvvm.read.ptx.sreg.warpsize`.
// TODO: Operation `nvvm.redux.sync`.
// TODO: Operation `nvvm.shfl.sync`.
// TODO: Operation `nvvm.vote.ballot.sync`.
// TODO: Operation `nvvm.wmma.load`.
// TODO: Operation `nvvm.wmma.mma`.
// TODO: Operation `nvvm.wmma.store`.
