// TODO: Operation `omp.atomic.capture`.
// TODO: Operation `omp.atomic.read`.
// TODO: Operation `omp.atomic.update`.
// TODO: Operation `omp.atomic.write`.
// TODO: Operation `omp.barrier`.
// TODO: Operation `omp.cancel`.
// TODO: Operation `omp.cancellationpoint`.
// TODO: Operation `omp.critical.declare`.
// TODO: Operation `omp.critical`.
// TODO: Operation `omp.flush`.
// TODO: Operation `omp.master`.
// TODO: Operation `omp.ordered`.
// TODO: Operation `omp.ordered_region`.
// TODO: Operation `omp.parallel`.
// TODO: Operation `omp.reduction.declare`.
// TODO: Operation `omp.reduction`.
// TODO: Operation `omp.section`.
// TODO: Operation `omp.sections`.
// TODO: Operation `omp.single`.
// TODO: Operation `omp.target`.
// TODO: Operation `omp.target_data`.
// TODO: Operation `omp.target_enter_data`.
// TODO: Operation `omp.target_exit_data`.
// TODO: Operation `omp.taskgroup`.
// TODO: Operation `omp.taskloop`.
// TODO: Operation `omp.task`.
// TODO: Operation `omp.taskwait`.
// TODO: Operation `omp.taskyield`.
// TODO: Operation `omp.terminator`.
// TODO: Operation `omp.threadprivate`.
// TODO: Operation `omp.wsloop`.
// TODO: Operation `omp.yield`.
