// TODO: Operation `pdl.apply_native_constraint`.
// TODO: Operation `pdl.apply_native_rewrite`.
// TODO: Operation `pdl.attribute`.
// TODO: Operation `pdl.erase`.
// TODO: Operation `pdl.operand`.
// TODO: Operation `pdl.operands`.
// TODO: Operation `pdl.operation`.
// TODO: Operation `pdl.pattern`.
// TODO: Operation `pdl.range`.
// TODO: Operation `pdl.replace`.
// TODO: Operation `pdl.result`.
// TODO: Operation `pdl.results`.
// TODO: Operation `pdl.rewrite`.
// TODO: Operation `pdl.type`.
// TODO: Operation `pdl.types`.
