// TODO: Operation `pdl_interp.apply_constraint`.
// TODO: Operation `pdl_interp.apply_rewrite`.
// TODO: Operation `pdl_interp.are_equal`.
// TODO: Operation `pdl_interp.branch`.
// TODO: Operation `pdl_interp.check_attribute`.
// TODO: Operation `pdl_interp.check_operand_count`.
// TODO: Operation `pdl_interp.check_operation_name`.
// TODO: Operation `pdl_interp.check_result_count`.
// TODO: Operation `pdl_interp.check_type`.
// TODO: Operation `pdl_interp.check_types`.
// TODO: Operation `pdl_interp.continue`.
// TODO: Operation `pdl_interp.create_attribute`.
// TODO: Operation `pdl_interp.create_operation`.
// TODO: Operation `pdl_interp.create_range`.
// TODO: Operation `pdl_interp.create_type`.
// TODO: Operation `pdl_interp.create_types`.
// TODO: Operation `pdl_interp.erase`.
// TODO: Operation `pdl_interp.extract`.
// TODO: Operation `pdl_interp.finalize`.
// TODO: Operation `pdl_interp.foreach`.
// TODO: Operation `pdl_interp.func`.
// TODO: Operation `pdl_interp.get_attribute_type`.
// TODO: Operation `pdl_interp.get_attribute`.
// TODO: Operation `pdl_interp.get_defining_op`.
// TODO: Operation `pdl_interp.get_operand`.
// TODO: Operation `pdl_interp.get_operands`.
// TODO: Operation `pdl_interp.get_result`.
// TODO: Operation `pdl_interp.get_results`.
// TODO: Operation `pdl_interp.get_users`.
// TODO: Operation `pdl_interp.get_value_type`.
// TODO: Operation `pdl_interp.is_not_null`.
// TODO: Operation `pdl_interp.record_match`.
// TODO: Operation `pdl_interp.replace`.
// TODO: Operation `pdl_interp.switch_attribute`.
// TODO: Operation `pdl_interp.switch_operand_count`.
// TODO: Operation `pdl_interp.switch_operation_name`.
// TODO: Operation `pdl_interp.switch_result_count`.
// TODO: Operation `pdl_interp.switch_type`.
// TODO: Operation `pdl_interp.switch_types`.
