// TODO: Operation `scf.condition`.
// TODO: Operation `scf.execute_region`.
// TODO: Operation `scf.for`.
// TODO: Operation `scf.forall`.
// TODO: Operation `scf.if`.
// TODO: Operation `scf.forall.in.parallel`.
// TODO: Operation `scf.index_switch`.
// TODO: Operation `scf.parallel`.
// TODO: Operation `scf.reduce`.
// TODO: Operation `scf.reduce.return`.
// TODO: Operation `scf.while`.
// TODO: Operation `scf.yield`.
