// TODO: Operation `shape.add`.
// TODO: Operation `shape.any`.
// TODO: Operation `shape.assuming_all`.
// TODO: Operation `shape.assuming_yield`.
// TODO: Operation `shape.assuming`.
// TODO: Operation `shape.broadcast`.
// TODO: Operation `shape.concat`.
// TODO: Operation `shape.const_shape`.
// TODO: Operation `shape.const_size`.
// TODO: Operation `shape.const_witness`.
// TODO: Operation `shape.cstr_broadcastable`.
// TODO: Operation `shape.cstr_eq`.
// TODO: Operation `shape.cstr_require`.
// TODO: Operation `shape.debug_print`.
// TODO: Operation `shape.dim`.
// TODO: Operation `shape.div`.
// TODO: Operation `shape.from_extent_tensor`.
// TODO: Operation `shape.from_extents`.
// TODO: Operation `shape.func`.
// TODO: Operation `shape.function_library`.
// TODO: Operation `shape.get_extent`.
// TODO: Operation `shape.index_to_size`.
// TODO: Operation `shape.is_broadcastable`.
// TODO: Operation `shape.max`.
// TODO: Operation `shape.meet`.
// TODO: Operation `shape.min`.
// TODO: Operation `shape.mul`.
// TODO: Operation `shape.num_elements`.
// TODO: Operation `shape.rank`.
// TODO: Operation `shape.reduce`.
// TODO: Operation `shape.return`.
// TODO: Operation `shape.shape_eq`.
// TODO: Operation `shape.shape_of`.
// TODO: Operation `shape.size_to_index`.
// TODO: Operation `shape.split_at`.
// TODO: Operation `shape.to_extent_tensor`.
// TODO: Operation `shape.value_as_shape`.
// TODO: Operation `shape.value_of`.
// TODO: Operation `shape.with_shape`.
// TODO: Operation `shape.yield`.
