// TODO: Operation `sparse_tensor.binary`.
// TODO: Operation `sparse_tensor.compress`.
// TODO: Operation `sparse_tensor.concatenate`.
// TODO: Operation `sparse_tensor.convert`.
// TODO: Operation `sparse_tensor.coordinates_buffer`.
// TODO: Operation `sparse_tensor.coordinates`.
// TODO: Operation `sparse_tensor.expand`.
// TODO: Operation `sparse_tensor.foreach`.
// TODO: Operation `sparse_tensor.insert`.
// TODO: Operation `sparse_tensor.load`.
// TODO: Operation `sparse_tensor.new`.
// TODO: Operation `sparse_tensor.number_of_entries`.
// TODO: Operation `sparse_tensor.out`.
// TODO: Operation `sparse_tensor.pack`.
// TODO: Operation `sparse_tensor.positions`.
// TODO: Operation `sparse_tensor.push_back`.
// TODO: Operation `sparse_tensor.reduce`.
// TODO: Operation `sparse_tensor.select`.
// TODO: Operation `sparse_tensor.slice.offset`.
// TODO: Operation `sparse_tensor.slice.stride`.
// TODO: Operation `sparse_tensor.sort_coo`.
// TODO: Operation `sparse_tensor.sort`.
// TODO: Operation `sparse_tensor.storage_specifier.get`.
// TODO: Operation `sparse_tensor.storage_specifier.init`.
// TODO: Operation `sparse_tensor.storage_specifier.set`.
// TODO: Operation `sparse_tensor.unary`.
// TODO: Operation `sparse_tensor.unpack`.
// TODO: Operation `sparse_tensor.values`.
// TODO: Operation `sparse_tensor.yield`.
