// TODO: Operation `spirv.AccessChain`.
// TODO: Operation `spirv.AtomicAnd`.
// TODO: Operation `spirv.AtomicCompareExchange`.
// TODO: Operation `spirv.AtomicCompareExchangeWeak`.
// TODO: Operation `spirv.AtomicExchange`.
// TODO: Operation `spirv.AtomicIAdd`.
// TODO: Operation `spirv.AtomicIDrecrement`.
// TODO: Operation `spirv.AtomicIIncrement`.
// TODO: Operation `spirv.AtomicISub`.
// TODO: Operation `spirv.AtomicOr`.
// TODO: Operation `spirv.AtomicSMax`.
// TODO: Operation `spirv.AtomicSMin`.
// TODO: Operation `spirv.AtomicUMax`.
// TODO: Operation `spirv.AtomicUMin`.
// TODO: Operation `spirv.AtomicXor`.
// TODO: Operation `spirv.Bitcast`.
// TODO: Operation `spirv.BitCount`.
// TODO: Operation `spirv.BitFieldInsert`.
// TODO: Operation `spirv.BitFieldSExtract`.
// TODO: Operation `spirv.BitFieldUExtract`.
// TODO: Operation `spirv.BitReverse`.
// TODO: Operation `spirv.BitwiseAnd`.
// TODO: Operation `spirv.BitwiseOr`.
// TODO: Operation `spirv.BitwiseXor`.
// TODO: Operation `spirv.Branch`.
// TODO: Operation `spirv.BranchConditional`.
// TODO: Operation `spirv.CL.ceil`.
// TODO: Operation `spirv.CL.cos`.
// TODO: Operation `spirv.CL.erf`.
// TODO: Operation `spirv.CL.exp`.
// TODO: Operation `spirv.CL.fabs`.
// TODO: Operation `spirv.CL.floor`.
// TODO: Operation `spirv.CL.fma`.
// TODO: Operation `spirv.CL.fmax`.
// TODO: Operation `spirv.CL.fmin`.
// TODO: Operation `spirv.CL.log`.
// TODO: Operation `spirv.CL.pow`.
// TODO: Operation `spirv.CL.printf`.
// TODO: Operation `spirv.CL.rint`.
// TODO: Operation `spirv.CL.round`.
// TODO: Operation `spirv.CL.rsqrt`.
// TODO: Operation `spirv.CL.s_abs`.
// TODO: Operation `spirv.CL.s_max`.
// TODO: Operation `spirv.CL.s_min`.
// TODO: Operation `spirv.CL.sin`.
// TODO: Operation `spirv.CL.sqrt`.
// TODO: Operation `spirv.CL.tanh`.
// TODO: Operation `spirv.CL.u_max`.
// TODO: Operation `spirv.CL.u_min`.
// TODO: Operation `spirv.CompositeConstruct`.
// TODO: Operation `spirv.CompositeExtract`.
// TODO: Operation `spirv.CompositeInsert`.
// TODO: Operation `spirv.Constant`.
// TODO: Operation `spirv.ControlBarrier`.
// TODO: Operation `spirv.ConvertFToS`.
// TODO: Operation `spirv.ConvertFToU`.
// TODO: Operation `spirv.ConvertPtrToU`.
// TODO: Operation `spirv.ConvertSToF`.
// TODO: Operation `spirv.ConvertUToF`.
// TODO: Operation `spirv.ConvertUToPtr`.
// TODO: Operation `spirv.CopyMemory`.
// TODO: Operation `spirv.EntryPoint`.
// TODO: Operation `spirv.ExecutionMode`.
// TODO: Operation `spirv.EXT.AtomicFAdd`.
// TODO: Operation `spirv.FAdd`.
// TODO: Operation `spirv.FConvert`.
// TODO: Operation `spirv.FDiv`.
// TODO: Operation `spirv.FMod`.
// TODO: Operation `spirv.FMul`.
// TODO: Operation `spirv.FNegate`.
// TODO: Operation `spirv.FOrdEqual`.
// TODO: Operation `spirv.FOrdGreaterThan`.
// TODO: Operation `spirv.FOrdGreaterThanEqual`.
// TODO: Operation `spirv.FOrdLessThan`.
// TODO: Operation `spirv.FOrdLessThanEqual`.
// TODO: Operation `spirv.FOrdNotEqual`.
// TODO: Operation `spirv.FRem`.
// TODO: Operation `spirv.FSub`.
// TODO: Operation `spirv.func`.
// TODO: Operation `spirv.FunctionCall`.
// TODO: Operation `spirv.FUnordEqual`.
// TODO: Operation `spirv.FUnordGreaterThan`.
// TODO: Operation `spirv.FUnordGreaterThanEqual`.
// TODO: Operation `spirv.FUnordLessThan`.
// TODO: Operation `spirv.FUnordLessThanEqual`.
// TODO: Operation `spirv.FUnordNotEqual`.
// TODO: Operation `spirv.GenericCastToPtr`.
// TODO: Operation `spirv.GenericCastToPtrExplicit`.
// TODO: Operation `spirv.GL.Acos`.
// TODO: Operation `spirv.GL.Asin`.
// TODO: Operation `spirv.GL.Ceil`.
// TODO: Operation `spirv.GL.Cos`.
// TODO: Operation `spirv.GL.Cosh`.
// TODO: Operation `spirv.GL.Exp`.
// TODO: Operation `spirv.GL.FAbs`.
// TODO: Operation `spirv.GL.FClamp`.
// TODO: Operation `spirv.GL.FindUMsb`.
// TODO: Operation `spirv.GL.Floor`.
// TODO: Operation `spirv.GL.Fma`.
// TODO: Operation `spirv.GL.FMax`.
// TODO: Operation `spirv.GL.FMin`.
// TODO: Operation `spirv.GL.FMix`.
// TODO: Operation `spirv.GL.FrexpStruct`.
// TODO: Operation `spirv.GL.FSign`.
// TODO: Operation `spirv.GL.InverseSqrt`.
// TODO: Operation `spirv.GL.Ldexp`.
// TODO: Operation `spirv.GL.Log`.
// TODO: Operation `spirv.GL.Pow`.
// TODO: Operation `spirv.GL.Round`.
// TODO: Operation `spirv.GL.RoundEven`.
// TODO: Operation `spirv.GL.SAbs`.
// TODO: Operation `spirv.GL.SClamp`.
// TODO: Operation `spirv.GL.Sin`.
// TODO: Operation `spirv.GL.Sinh`.
// TODO: Operation `spirv.GL.SMax`.
// TODO: Operation `spirv.GL.SMin`.
// TODO: Operation `spirv.GL.Sqrt`.
// TODO: Operation `spirv.GL.SSign`.
// TODO: Operation `spirv.GL.Tan`.
// TODO: Operation `spirv.GL.Tanh`.
// TODO: Operation `spirv.GL.UClamp`.
// TODO: Operation `spirv.GL.UMax`.
// TODO: Operation `spirv.GL.UMin`.
// TODO: Operation `spirv.GlobalVariable`.
// TODO: Operation `spirv.GroupBroadcast`.
// TODO: Operation `spirv.GroupFAdd`.
// TODO: Operation `spirv.GroupFMax`.
// TODO: Operation `spirv.GroupFMin`.
// TODO: Operation `spirv.GroupIAdd`.
// TODO: Operation `spirv.GroupNonUniformBallot`.
// TODO: Operation `spirv.GroupNonUniformBroadcast`.
// TODO: Operation `spirv.GroupNonUniformElect`.
// TODO: Operation `spirv.GroupNonUniformFAdd`.
// TODO: Operation `spirv.GroupNonUniformFMax`.
// TODO: Operation `spirv.GroupNonUniformFMin`.
// TODO: Operation `spirv.GroupNonUniformFMul`.
// TODO: Operation `spirv.GroupNonUniformIAdd`.
// TODO: Operation `spirv.GroupNonUniformIMul`.
// TODO: Operation `spirv.GroupNonUniformShuffle`.
// TODO: Operation `spirv.GroupNonUniformShuffleDown`.
// TODO: Operation `spirv.GroupNonUniformShuffleUp`.
// TODO: Operation `spirv.GroupNonUniformShuffleXor`.
// TODO: Operation `spirv.GroupNonUniformSMax`.
// TODO: Operation `spirv.GroupNonUniformSMin`.
// TODO: Operation `spirv.GroupNonUniformUMax`.
// TODO: Operation `spirv.GroupNonUniformUMin`.
// TODO: Operation `spirv.GroupSMax`.
// TODO: Operation `spirv.GroupSMin`.
// TODO: Operation `spirv.GroupUMax`.
// TODO: Operation `spirv.GroupUMin`.
// TODO: Operation `spirv.IAdd`.
// TODO: Operation `spirv.IAddCarry`.
// TODO: Operation `spirv.IEqual`.
// TODO: Operation `spirv.Image`.
// TODO: Operation `spirv.ImageDrefGather`.
// TODO: Operation `spirv.ImageQuerySize`.
// TODO: Operation `spirv.IMul`.
// TODO: Operation `spirv.InBoundsPtrAccessChain`.
// TODO: Operation `spirv.INotEqual`.
// TODO: Operation `spirv.INTEL.ConvertBF16ToF`.
// TODO: Operation `spirv.INTEL.ConvertFToBF16`.
// TODO: Operation `spirv.INTEL.JointMatrixLoad`.
// TODO: Operation `spirv.INTEL.JointMatrixMad`.
// TODO: Operation `spirv.INTEL.JointMatrixStore`.
// TODO: Operation `spirv.INTEL.JointMatrixWorkItemLength`.
// TODO: Operation `spirv.INTEL.SubgroupBlockRead`.
// TODO: Operation `spirv.INTEL.SubgroupBlockWrite`.
// TODO: Operation `spirv.IsInf`.
// TODO: Operation `spirv.IsNan`.
// TODO: Operation `spirv.ISub`.
// TODO: Operation `spirv.ISubBorrow`.
// TODO: Operation `spirv.KHR.AssumeTrue`.
// TODO: Operation `spirv.KHR.GroupFMul`.
// TODO: Operation `spirv.KHR.GroupIMul`.
// TODO: Operation `spirv.KHR.SubgroupBallot`.
// TODO: Operation `spirv.Load`.
// TODO: Operation `spirv.LogicalAnd`.
// TODO: Operation `spirv.LogicalEqual`.
// TODO: Operation `spirv.LogicalNot`.
// TODO: Operation `spirv.LogicalNotEqual`.
// TODO: Operation `spirv.LogicalOr`.
// TODO: Operation `spirv.MatrixTimesMatrix`.
// TODO: Operation `spirv.MatrixTimesScalar`.
// TODO: Operation `spirv.MemoryBarrier`.
// TODO: Operation `spirv.mlir.addressof`.
// TODO: Operation `spirv.mlir.loop`.
// TODO: Operation `spirv.mlir.merge`.
// TODO: Operation `spirv.mlir.referenceof`.
// TODO: Operation `spirv.mlir.selection`.
// TODO: Operation `spirv.mlir.yield`.
// TODO: Operation `spirv.module`.
// TODO: Operation `spirv.Not`.
// TODO: Operation `spirv.NV.CooperativeMatrixLength`.
// TODO: Operation `spirv.NV.CooperativeMatrixLoad`.
// TODO: Operation `spirv.NV.CooperativeMatrixMulAdd`.
// TODO: Operation `spirv.NV.CooperativeMatrixStore`.
// TODO: Operation `spirv.Ordered`.
// TODO: Operation `spirv.PtrAccessChain`.
// TODO: Operation `spirv.PtrCastToGeneric`.
// TODO: Operation `spirv.Return`.
// TODO: Operation `spirv.ReturnValue`.
// TODO: Operation `spirv.SConvert`.
// TODO: Operation `spirv.SDiv`.
// TODO: Operation `spirv.SDot`.
// TODO: Operation `spirv.SDotAccSat`.
// TODO: Operation `spirv.Select`.
// TODO: Operation `spirv.SGreaterThan`.
// TODO: Operation `spirv.SGreaterThanEqual`.
// TODO: Operation `spirv.ShiftLeftLogical`.
// TODO: Operation `spirv.ShiftRightArithmetic`.
// TODO: Operation `spirv.ShiftRightLogical`.
// TODO: Operation `spirv.SLessThan`.
// TODO: Operation `spirv.SLessThanEqual`.
// TODO: Operation `spirv.SMod`.
// TODO: Operation `spirv.SMulExtended`.
// TODO: Operation `spirv.SNegate`.
// TODO: Operation `spirv.SpecConstant`.
// TODO: Operation `spirv.SpecConstantComposite`.
// TODO: Operation `spirv.SpecConstantOperation`.
// TODO: Operation `spirv.SRem`.
// TODO: Operation `spirv.Store`.
// TODO: Operation `spirv.SUDot`.
// TODO: Operation `spirv.SUDotAccSat`.
// TODO: Operation `spirv.Transpose`.
// TODO: Operation `spirv.UConvert`.
// TODO: Operation `spirv.UDiv`.
// TODO: Operation `spirv.UDot`.
// TODO: Operation `spirv.UDotAccSat`.
// TODO: Operation `spirv.UGreaterThan`.
// TODO: Operation `spirv.UGreaterThanEqual`.
// TODO: Operation `spirv.ULessThan`.
// TODO: Operation `spirv.ULessThanEqual`.
// TODO: Operation `spirv.UMod`.
// TODO: Operation `spirv.UMulExtended`.
// TODO: Operation `spirv.Undef`.
// TODO: Operation `spirv.Unordered`.
// TODO: Operation `spirv.Unreachable`.
// TODO: Operation `spirv.Variable`.
// TODO: Operation `spirv.VectorExtractDynamic`.
// TODO: Operation `spirv.VectorInsertDynamic`.
// TODO: Operation `spirv.VectorShuffle`.
// TODO: Operation `spirv.VectorTimesScalar`.
