// TODO: Operation `tensor.bitcast`.
// TODO: Operation `tensor.cast`.
// TODO: Operation `tensor.collapse_shape`.
// TODO: Operation `tensor.dim`.
// TODO: Operation `tensor.empty`.
// TODO: Operation `tensor.expand_shape`.
// TODO: Operation `tensor.extract`.
// TODO: Operation `tensor.extract_slice`.
// TODO: Operation `tensor.from_elements`.
// TODO: Operation `tensor.gather`.
// TODO: Operation `tensor.generate`.
// TODO: Operation `tensor.insert`.
// TODO: Operation `tensor.insert_slice`.
// TODO: Operation `tensor.pack`.
// TODO: Operation `tensor.pad`.
// TODO: Operation `tensor.parallel_insert_slice`.
// TODO: Operation `tensor.rank`.
// TODO: Operation `tensor.reshape`.
// TODO: Operation `tensor.scatter`.
// TODO: Operation `tensor.splat`.
// TODO: Operation `tensor.unpack`.
// TODO: Operation `tensor.yield`.
