// TODO: Operation `tosa.abs`.
// TODO: Operation `tosa.add`.
// TODO: Operation `tosa.apply_scale`.
// TODO: Operation `tosa.argmax`.
// TODO: Operation `tosa.arithmetic_right_shift`.
// TODO: Operation `tosa.avg_pool2d`.
// TODO: Operation `tosa.bitwise_and`.
// TODO: Operation `tosa.bitwise_not`.
// TODO: Operation `tosa.bitwise_or`.
// TODO: Operation `tosa.bitwise_xor`.
// TODO: Operation `tosa.cast`.
// TODO: Operation `tosa.ceil`.
// TODO: Operation `tosa.clamp`.
// TODO: Operation `tosa.clz`.
// TODO: Operation `tosa.concat`.
// TODO: Operation `tosa.cond_if`.
// TODO: Operation `tosa.const`.
// TODO: Operation `tosa.conv2d`.
// TODO: Operation `tosa.conv3d`.
// TODO: Operation `tosa.custom`.
// TODO: Operation `tosa.depthwise_conv2d`.
// TODO: Operation `tosa.div`.
// TODO: Operation `tosa.equal`.
// TODO: Operation `tosa.erf`.
// TODO: Operation `tosa.exp`.
// TODO: Operation `tosa.fft2d`.
// TODO: Operation `tosa.floor`.
// TODO: Operation `tosa.fully_connected`.
// TODO: Operation `tosa.gather`.
// TODO: Operation `tosa.greater_equal`.
// TODO: Operation `tosa.greater`.
// TODO: Operation `tosa.identity`.
// TODO: Operation `tosa.log`.
// TODO: Operation `tosa.logical_and`.
// TODO: Operation `tosa.logical_left_shift`.
// TODO: Operation `tosa.logical_not`.
// TODO: Operation `tosa.logical_or`.
// TODO: Operation `tosa.logical_right_shift`.
// TODO: Operation `tosa.logical_xor`.
// TODO: Operation `tosa.matmul`.
// TODO: Operation `tosa.max_pool2d`.
// TODO: Operation `tosa.maximum`.
// TODO: Operation `tosa.minimum`.
// TODO: Operation `tosa.mul`.
// TODO: Operation `tosa.negate`.
// TODO: Operation `tosa.pad`.
// TODO: Operation `tosa.pow`.
// TODO: Operation `tosa.reciprocal`.
// TODO: Operation `tosa.reduce_all`.
// TODO: Operation `tosa.reduce_any`.
// TODO: Operation `tosa.reduce_max`.
// TODO: Operation `tosa.reduce_min`.
// TODO: Operation `tosa.reduce_prod`.
// TODO: Operation `tosa.reduce_sum`.
// TODO: Operation `tosa.rescale`.
// TODO: Operation `tosa.reshape`.
// TODO: Operation `tosa.resize`.
// TODO: Operation `tosa.reverse`.
// TODO: Operation `tosa.rfft2d`.
// TODO: Operation `tosa.rsqrt`.
// TODO: Operation `tosa.scatter`.
// TODO: Operation `tosa.select`.
// TODO: Operation `tosa.sigmoid`.
// TODO: Operation `tosa.slice`.
// TODO: Operation `tosa.sub`.
// TODO: Operation `tosa.table`.
// TODO: Operation `tosa.tanh`.
// TODO: Operation `tosa.tile`.
// TODO: Operation `tosa.transpose_conv2d`.
// TODO: Operation `tosa.transpose`.
// TODO: Operation `tosa.while_loop`.
// TODO: Operation `tosa.yield`.
