// TODO: Operation `transform.affine.simplify_bounded_affine_ops`.
// TODO: Operation `transform.alternatives`.
// TODO: Operation `transform.annotate`.
// TODO: Operation `transform.apply_patterns`.
// TODO: Operation `transform.bufferization.eliminate_empty_tensors`.
// TODO: Operation `transform.bufferization.empty_tensor_to_alloc_tensor`.
// TODO: Operation `transform.bufferization.one_shot_bufferize`.
// TODO: Operation `transform.cast`.
// TODO: Operation `transform.foreach_match`.
// TODO: Operation `transform.foreach`.
// TODO: Operation `transform.get_closest_isolated_parent`.
// TODO: Operation `transform.get_consumers_of_result`.
// TODO: Operation `transform.get_defining_op`.
// TODO: Operation `transform.get_producer_of_operand`.
// TODO: Operation `transform.get_result`.
// TODO: Operation `transform.gpu.map_forall_to_blocks`.
// TODO: Operation `transform.gpu.map_nested_forall_to_threads`.
// TODO: Operation `transform.include`.
// TODO: Operation `transform.loop.coalesce`.
// TODO: Operation `transform.loop.get_parent_for`.
// TODO: Operation `transform.loop.outline`.
// TODO: Operation `transform.loop.peel`.
// TODO: Operation `transform.loop.pipeline`.
// TODO: Operation `transform.loop.unroll`.
// TODO: Operation `transform.match.operation_name`.
// TODO: Operation `transform.match.param.cmpi`.
// TODO: Operation `transform.match.structured.body`.
// TODO: Operation `transform.match.structured.dim`.
// TODO: Operation `transform.match.structured.elemental_bitwidth`.
// TODO: Operation `transform.match.structured.init`.
// TODO: Operation `transform.match.structured.input`.
// TODO: Operation `transform.match.structured.num_inits`.
// TODO: Operation `transform.match.structured.num_inputs`.
// TODO: Operation `transform.match.structured.rank`.
// TODO: Operation `transform.match.structured.result`.
// TODO: Operation `transform.match.structured.yield`.
// TODO: Operation `transform.match.structured`.
// TODO: Operation `transform.memref.extract_address_computations`.
// TODO: Operation `transform.memref.make_loop_independent`.
// TODO: Operation `transform.memref.multibuffer`.
// TODO: Operation `transform.merge_handles`.
// TODO: Operation `transform.named_sequence`.
// TODO: Operation `transform.param.constant`.
// TODO: Operation `transform.pdl_match`.
// TODO: Operation `transform.print`.
// TODO: Operation `transform.replicate`.
// TODO: Operation `transform.scf.take_assumed_branch`.
// TODO: Operation `transform.sequence`.
// TODO: Operation `transform.split_handle`.
// TODO: Operation `transform.structured.bufferize_to_allocation`.
// TODO: Operation `transform.structured.convert_conv2d_to_img2col`.
// TODO: Operation `transform.structured.decompose`.
// TODO: Operation `transform.structured.fuse_into_containing_op`.
// TODO: Operation `transform.structured.fuse`.
// TODO: Operation `transform.structured.generalize`.
// TODO: Operation `transform.structured.hoist_pad.build_packing_loop_nest`.
// TODO: Operation `transform.structured.hoist_pad`.
// TODO: Operation `transform.structured.hoist_redundant_tensor_subsets`.
// TODO: Operation `transform.structured.hoist_redundant_vector_transfers`.
// TODO: Operation `transform.structured.insert_slice_to_copy`.
// TODO: Operation `transform.structured.interchange`.
// TODO: Operation `transform.structured.lower_pack`.
// TODO: Operation `transform.structured.lower_unpack`.
// TODO: Operation `transform.structured.masked_vectorize`.
// TODO: Operation `transform.structured.match`.
// TODO: Operation `transform.structured.multitile_sizes`.
// TODO: Operation `transform.structured.pack_greedily`.
// TODO: Operation `transform.structured.pack_transpose`.
// TODO: Operation `transform.structured.pack`.
// TODO: Operation `transform.structured.pad`.
// TODO: Operation `transform.structured.promote`.
// TODO: Operation `transform.structured.replace`.
// TODO: Operation `transform.structured.rewrite_in_destination_passing_style`.
// TODO: Operation `transform.structured.scalarize`.
// TODO: Operation `transform.structured.split_reduction`.
// TODO: Operation `transform.structured.split`.
// TODO: Operation `transform.structured.tile_reduction_using_forall`.
// TODO: Operation `transform.structured.tile_reduction_using_scf`.
// TODO: Operation `transform.structured.tile_to_forall_op`.
// TODO: Operation `transform.structured.tile_to_scf_for`.
// TODO: Operation `transform.structured.tile`.
// TODO: Operation `transform.structured.vectorize`.
// TODO: Operation `transform.tensor.make_loop_independent`.
// TODO: Operation `transform.vector.apply_rank_reducing_subview_patterns`.
// TODO: Operation `transform.vector.apply_transfer_permutation_patterns`.
// TODO: Operation `transform.vector.lower_broadcast`.
// TODO: Operation `transform.vector.lower_contraction`.
// TODO: Operation `transform.vector.lower_masked_transfers`.
// TODO: Operation `transform.vector.lower_masks`.
// TODO: Operation `transform.vector.lower_multi_reduction`.
// TODO: Operation `transform.vector.lower_outerproduct`.
// TODO: Operation `transform.vector.lower_shape_cast`.
// TODO: Operation `transform.vector.lower_transfer`.
// TODO: Operation `transform.vector.lower_transpose`.
// TODO: Operation `transform.vector.materialize_masks`.
// TODO: Operation `transform.vector.split_transfer_full_partial`.
// TODO: Operation `transform.vector.transfer_to_scf`.
// TODO: Operation `transform.with_pdl_patterns`.
// TODO: Operation `transform.yield`.
