// TODO: Operation `vector.bitcast`.
// TODO: Operation `vector.broadcast`.
// TODO: Operation `vector.compressstore`.
// TODO: Operation `vector.constant_mask`.
// TODO: Operation `vector.contract`.
// TODO: Operation `vector.create_mask`.
// TODO: Operation `vector.expandload`.
// TODO: Operation `vector.extract_strided_slice`.
// TODO: Operation `vector.extract`.
// TODO: Operation `vector.extractelement`.
// TODO: Operation `vector.flat_transpose`.
// TODO: Operation `vector.fma`.
// TODO: Operation `vector.gather`.
// TODO: Operation `vector.insert_strided_slice`.
// TODO: Operation `vector.insert`.
// TODO: Operation `vector.insertelement`.
// TODO: Operation `vector.load`.
// TODO: Operation `vector.mask`.
// TODO: Operation `vector.maskedload`.
// TODO: Operation `vector.maskedstore`.
// TODO: Operation `vector.matrix_multiply`.
// TODO: Operation `vector.multi_reduction`.
// TODO: Operation `vector.outerproduct`.
// TODO: Operation `vector.print`.
// TODO: Operation `vector.reduction`.
// TODO: Operation `vector.reshape`.
// TODO: Operation `vector.scalable.extract`.
// TODO: Operation `vector.scalable.insert`.
// TODO: Operation `vector.scan`.
// TODO: Operation `vector.scatter`.
// TODO: Operation `vector.shape_cast`.
// TODO: Operation `vector.shuffle`.
// TODO: Operation `vector.splat`.
// TODO: Operation `vector.store`.
// TODO: Operation `vector.transfer_read`.
// TODO: Operation `vector.transfer_write`.
// TODO: Operation `vector.transpose`.
// TODO: Operation `vector.type_cast`.
// TODO: Operation `vector.vscale`.
// TODO: Operation `vector.warp_execute_on_lane_0`.
// TODO: Operation `vector.yield`.
