[workspace]
resolver = "2"

default-members = [
    "crates/mulir",
    "crates/mulir-sys",
]
members = [
    "crates/mulir",
    "crates/mulir-sys",
    "crates/mulir-sys-codegen",
    "crates/mulir-sys-proc",
]
