[workspace]
resolver = "2"
members = [
    "crates/mithril-oxide",
    "crates/mithril-oxide-sys",
    "crates/mithril-oxide-sys-codegen",
    "crates/mithril-oxide-sys-proc",
]

[profile.ci-coverage]
inherits = "dev"
opt-level = 3
debug = true
