[package]
name = "mithril-oxide-sys-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
clang = { version = "2.0.0", features = ["clang_10_0"] }
proc-macro2 = "1.0.60"
quote = "1.0.28"
syn = { version = "2.0.18", features = ["extra-traits", "full"] }
tempfile = "3.6.0"
