[package]
name = "mithril-oxide-sys-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
clang = { version = "2.0.0", features = ["clang_10_0"] }
proc-macro2 = "1.0.58"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["extra-traits", "full"] }
tempfile = "3.5.0"
