[package]
name = "mithril-oxide-sys-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.58"
mithril-oxide-sys-codegen = { path = "../mithril-oxide-sys-codegen", artifact = "bin" }
