[package]
name = "mulir-sys-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
clang = "2.0.0"
proc-macro2 = "1.0.58"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["extra-traits", "full"] }
